export { HomeView } from "./HomeView";
export { GalleryView } from "./GalleryView";
export { SPLTokenView } from "./SPLTokenView";
export { UploadView } from "./UploadView";
export { SUATMMView } from "./SUATM²View";
export { MultiSenderView } from "./MultiSenderView"
export { BurnSPLView } from "./BurnSPLView"
export { CloseAccountView } from "./CloseAccountView"
export { UpdateNFTMetadataView } from "./UpdateNFTMetadataView";