export const BURN_CU = 4800;
export const CLOSE_ACCOUNT_CU = 3000;
export const HARVEST_TOKENS_CU = 2000;
export const WITHDRAW_TRANSFER_FEES_FOR_ONE_ACCOUNT_CU = 2000;
export const WITHDRAW_TRANSFER_FEES_FOR_ADDITIONAL_ACCOUNT_CU = 400;
export const ADD_COMPUTE_UNIT_PRICE_CU = 150;
export const ADD_COMPUTE_UNIT_LIMIT_CU = 150;
export const SOL_TRANSFER_CU = 150;